version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-asset
    ports:
      - "5441:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: asset_management
    volumes:
      - pgdata-asset:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-asset
    ports:
      - "3009:3009"
    depends_on:
      - postgres

  employee-asset-ui:
    build: ./Employee-Asset
    container_name: employee-asset-ui
    ports:
      - "8014:80"

  hr-asset-ui:
    build: ./Hr-Asset
    container_name: hr-asset-ui
    ports:
      - "8015:80"

volumes:
  pgdata-asset:

